// client/src/App.jsx
import './App.css'
import { Image, Alert, Button, Container, Row, Col, Form, Table, Stack } from 'react-bootstrap'
import React, { useState, useEffect } from 'react'

import axios from 'axios'

const App = () => {
  const [description, setDescription] = useState('')
  const [items, setItems] = useState([])

  useEffect(() => {
    // todo
  }, [])

  const renderAddTodoItemContent = () => {
    return (
      <Container>
        <h1>Add Item</h1>
        <Form.Group as={Row} className="mb-3" controlId="formAddTodoItem">
          <Form.Label column sm="2">
            Description
          </Form.Label>
          <Col md="6">
            <Form.Control
              type="text"
              placeholder="Enter description..."
              value={description}
              onChange={handleDescriptionChange}
            />
          </Col>
        </Form.Group>
        <Form.Group as={Row} className="mb-3 offset-md-2" controlId="formAddTodoItem">
          <Stack direction="horizontal" gap={2}>
            <Button variant="primary" onClick={() => handleAdd()}>
              Add Item
            </Button>
            <Button variant="secondary" onClick={() => handleClear()}>
              Clear
            </Button>
          </Stack>
        </Form.Group>
      </Container>
    )
  }

  const renderTodoItemsContent = () => {
    return (
      <>
        <h1>
          Showing {items.length} Item(s){' '}
          <Button variant="primary" className="pull-right" onClick={() => getItems()}>
            Refresh
          </Button>
        </h1>

        <Table striped bordered hover>
          <thead>
            <tr>
              <th>Id</th>
              <th>Description</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id}>
                <td>{item.id}</td>
                <td>{item.description}</td>
                <td>
                  <Button variant="warning" size="sm" onClick={() => handleMarkAsComplete(item)}>
                    Mark as completed
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </Table>
      </>
    )
  }

  const handleDescriptionChange = (event) => {
    // todo
  }

  async function getItems() {
    try {
      alert('todo')
    } catch (error) {
      console.error(error)
    }
  }

  async function handleAdd() {
    try {
      alert('todo')
    } catch (error) {
      console.error(error)
    }
  }

  function handleClear() {
    setDescription('')
  }

  async function handleMarkAsComplete(item) {
    try {
      alert('todo')
    } catch (error) {
      console.error(error)
    }
  }

  return (
    <div className="App">
      <Container>
        <Row>
          <Col>
            <Image src="clearPointLogo.png" fluid rounded />
          </Col>
        </Row>
        <Row>
          <Col>
            <Alert variant="success">
              <Alert.Heading>Todo List App</Alert.Heading>
              Welcome to the ClearPoint frontend technical test. We like to keep things simple, yet clean so your
              task(s) are as follows:
              <br />
              <br />
              <ol className="list-left">
                <li>Add the ability to add (POST) a Todo Item by calling the backend API</li>
                <li>
                  Display (GET) all the current Todo Items in the below grid and display them in any order you wish
                </li>
                <li>
                  Bonus points for completing the 'Mark as completed' button code for allowing users to update and mark
                  a specific Todo Item as completed and for displaying any relevant validation errors/ messages from the
                  API in the UI
                </li>
                <li>Feel free to add unit tests and refactor the component(s) as best you see fit</li>
              </ol>
            </Alert>
          </Col>
        </Row>
        <Row>
          <Col>{renderAddTodoItemContent()}</Col>
        </Row>
        <br />
        <Row>
          <Col>{renderTodoItemsContent()}</Col>
        </Row>
      </Container>
      <footer className="page-footer font-small teal pt-4">
        <div className="footer-copyright text-center py-3">
          © 2021 Copyright:
          <a href="https://clearpoint.digital" target="_blank" rel="noreferrer">
            clearpoint.digital
          </a>
        </div>
      </footer>
    </div>
  )
}

export default App

// Frontend-Angular/src/app/features/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { TodoItem } from 'src/app/models/todoitem';
import { TodoService } from 'src/app/service/todo.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  items: TodoItem[] = [];
  description: string = '';

  itemInEditing: TodoItem = null;

  public constructor(
    /** @internal */
    private service: TodoService
  ) {}

  ngOnInit(): void {
    this.getItems();
  }

  getItems() {
    this.service.fetch().subscribe((response: TodoItem[]) => {
      if (response) {
        this.items = response;
      }
    });
  }

  handleAdd() {
    const item = {
      id: crypto.randomUUID(),
      description: this.description,
      isCompleted: false
    }

    this.service.create(item).subscribe(() => {
      this.getItems();
    });
  }

  handleClear() {
    this.description = '';
    this.itemInEditing = null;
  }

  handleMarkAsComplete(item: TodoItem) {
    item.isCompleted = true;

    this.service.update(item).subscribe(() => {
      this.getItems();
    });
  }

  handleEdit(item: TodoItem) {
    if (this.itemInEditing)
    {
      alert('You are already editing an item!');
    } else {
      this.itemInEditing = item;
      this.description = item.description;
    }
  }

  handleUpdate() {
    this.itemInEditing.description = this.description;

    this.service.update(this.itemInEditing).subscribe(() => {      
      this.handleClear();
      this.getItems();
    });
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <img
        src="/assets/images/clearPointLogo.png"
        alt="ClearPoint"
        class="img-fluid rounded"
      />
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div role="alert" class="fade alert alert-success show">
        <div class="alert-heading h4">Todo List App (Angular)</div>
        Welcome to the ClearPoint frontend technical test. We like to keep
        things simple, yet clean so your task(s) are as follows:<br /><br />

        <ol class="list-left text-left">
          <li>
            Add the ability to add (POST) a Todo Item by calling the backend API
          </li>
          <li>
            Display (GET) all the current Todo Items in the below grid and
            display them in any order you wish
          </li>
          <li>
            Bonus points for completing the 'Mark as completed' button code for
            allowing users to update and mark a specific Todo Item as completed
            and for displaying any relevant validation errors/ messages from the
            API in the UI
          </li>
          <li>
            Feel free to add unit tests and refactor the component(s) as best
            you see fit
          </li>
        </ol>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="container">
        <h1>Add Item</h1>
        <div class="mb-3 row">
          <label
            for="formAddTodoItem"
            class="form-label col-form-label col-sm-2"
            >Description</label
          >
          <div class="col-md-6">
            <input
              placeholder="Enter description..."
              type="text"
              id="formAddTodoItem"
              class="form-control"
              [(ngModel)]="description"
            />
          </div>
        </div>
        <div class="mb-3 offset-md-2 row">
          <div class="hstack gap-2">
            <button id="add_button" *ngIf="!itemInEditing" type="button" class="btn btn-primary" (click)="handleAdd()">
              Add Item
            </button>
            <button *ngIf="itemInEditing" type="button" class="btn btn-primary" (click)="handleUpdate()">
              Update Item
            </button>
            <button
              type="button"
              class="btn btn-secondary"
              (click)="handleClear()"
            >
              Clear
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h1>
          Showing {{ items.length }} Item(s)
          <button
            type="button"
            class="pull-right btn btn-primary"
            (click)="getItems()"
          >
            Refresh
          </button>
        </h1>
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Id</th>
              <th>Description</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let item of items">
              <td>{{ item.id }}</td>
              <td>{{ item.description }}</td>
              <td>
                <div class="hstack gap-2">
                  <button
                    type="button"
                    class="btn btn-warning btn-sm"
                    (click)="handleMarkAsComplete(item)"
                  >
                    Mark as completed
                  </button>
                  <button
                    type="button"
                    class="btn btn-warning btn-sm"
                    (click)="handleEdit(item)"
                  >
                    Edit
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      © 2021 Copyright:
      <a href="https://clearpoint.digital" target="_blank" rel="noreferrer">
        clearpoint.digital
      </a>
    </div>
  </div>
</div>
